name: master.yml
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: '30/10 * * * *'
jobs:
    test_app:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os : [ubuntu-18.04, ubuntu-latest, macos-lates]
                version_node: [15, 16, 20]
        steps:
            - uses: actions/checkout@v4
            - name: Использование Node.js ${{ matrix.version_node }}
              uses: actions/setup-node@v1
              with:
                node-version: $ {{ matrix.version_node }}
            - run: npm ci
            - name: Run test_app
              uses: actions/run-tests@v1
    test_app_for_windows:
        needs: test_app
        runs-on: windows-2019
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run tests
              uses: actions/run-tests@v1
