name: master.yml

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30/10 * * * *'

jobs:
  test_app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-latest]
        version_node: [15, 16, 20]
    steps:
      - name: Run test for Linux
        run: echo "test for Linux"

  test_app_for_windows:
    needs: test_app
    runs-on: windows-2019
    steps:
      - name: Run test for Windows
        run: echo "test for Windows"
