name: master.yml
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30/10 * * * *'

jobs:
  test_app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-latest]
        version_node: [15, 16, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.version_node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version_node }}
      - run: npm ci

  test_app_for_windows:
    needs: test_app
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
